gestion_user_homepage:
    path:     /login
    defaults: { _controller: GestionUserBundle:Default:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

index_user:
    path:     /
    defaults: { _controller: GestionUserBundle:Default:indexuser }
index_admin:
    path:     /admin/index
    defaults: { _controller: GestionUserBundle:Default:indexadmin }
perso_profile_admin:
    path:     /admin/perso/profile/{id}
    defaults: { _controller: GestionUserBundle:Admin:perso_profile }

