gestion_service:
    resource: "@GestionServiceBundle/Resources/config/routing.yml"
    prefix:   /

gestion_user:
    resource: "@GestionUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

accessory:
    resource: "@AccessoryBundle/Resources/config/routing.yml"
    prefix:   /
