<?php

namespace AccessoryBundle\Controller;

use AccessoryBundle\Entity\Accessory;
use AccessoryBundle\Form\AccessoryType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;

use Symfony\Component\HttpFoundation\Request;


class AccessoryController extends Controller
{
    public function showAction(Accessory $accessory)
    {
        $accessories = $this->getDoctrine()->getManager()->getRepository(Accessory::class)->findAll();
        return $this->render('@Accessory/Accessory/show.html.twig', array(
            "accessory"=>$accessory,
            "accessories"=>$accessories
        ));
    }
    public function testAction(){
        $accessories = $this->getDoctrine()->getManager()->getRepository(Accessory::class)->findAll();
        return $this->render('@Accessory/Accessory/testlayout.html.twig',array(
            "accessories"=>$accessories
        ));
    }

    public function listAction()
    {
        $accessories = $this->getDoctrine()->getManager()->getRepository(Accessory::class)->findAll();
        return $this->render('@Accessory/Accessory/list.html.twig', array(
            "accessories"=>$accessories
        ));
    }
    public function AdminlistAction()
    {
        $accessories = $this->getDoctrine()->getManager()->getRepository(Accessory::class)->findAll();
        return $this->render('@Accessory/Accessory/adminList.html.twig', array(
            "accessories"=>$accessories
        ));
    }
    public function UpdateAction(Accessory $accessory,Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $tmpfile= $accessory->getImageUrl();

        if  ($request->isMethod('post')) {

            if ($_FILES['img']['tmp_name']!="") {
                $file = new UploadedFile($_FILES['img']['tmp_name'], 'test');

                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
                $file->move(
                    $this->getParameter('img_directory'),
                    $fileName
                );
                unlink($tmpfile);
                $accessory->setImageUrl('uploads/'.$fileName);
            }

            $accessory->setDescription($request->get('description'));
            $accessory->setName($request->get('name'));
            $accessory->setPrice($request->get('price'));
            $accessory->setStock($request->get('stock'));
            $accessory->setType($request->get('type'));
            $accessory->setInserted(new \DateTime());

            $em->persist($accessory);
            $em->flush();
            return $this->redirectToRoute('AdminList');
        }


        return $this->render('@Accessory/Accessory/update.html.twig', array(
            "accessory"=>$accessory
        ));
    }

    public function AddAction(Request $request){
        $em = $this->getDoctrine()->getManager();
        $accessory = new Accessory();

        if  ($request->isMethod('post')) {

          $file = new UploadedFile($_FILES['img']['tmp_name'],'test');

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            $file->move(
                $this->getParameter('img_directory'),
                $fileName
            );

            $accessory->setImageUrl('uploads/'.$fileName);
            $accessory->setDescription($request->get('description'));
            $accessory->setName($request->get('name'));
            $accessory->setPrice($request->get('price'));
            $accessory->setStock($request->get('stock'));
            $accessory->setType($request->get('type'));
            $accessory->setInserted(new \DateTime());

            $em->persist($accessory);
            $em->flush();
            return $this->redirectToRoute('AdminList');
        }
        return $this->render('@Accessory/Accessory/add.html.twig',
            array());
    }
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    public function DeleteAction(Accessory $accessory){
        $em = $this->getDoctrine()->getManager();
        $file = $accessory->getImageUrl();

        unlink($file);
        $em->remove($accessory);
        $em->flush();

        return $this->redirectToRoute('AdminList');

    }

}
